# Generated by Django 2.2 on 2021-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210614_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerselected',
            old_name='answer_selected',
            new_name='related_quiz',
        ),
        migrations.RemoveField(
            model_name='answerselected',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='answerselected',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizhistory',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='quizhistory',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='quizhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='answerselected',
            name='answers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
