# Generated by Django 2.2 on 2021-06-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210614_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerselected',
            old_name='answers',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answerselected',
            old_name='related_quiz',
            new_name='quiz_history',
        ),
    ]
